custom library spec
match capacity with backend

updated library contents for custom library

updated gitignore

diff --git a/etc/generate_device_conf.in b/etc/generate_device_conf.in
--- a/etc/generate_device_conf.in
+++ b/etc/generate_device_conf.in
@@ -378,6 +378,27 @@ add_library_contents_30()
 	add_stk_t10kb_drive 34 0 12 0 "XYZZY_B4" 30 4
 }
 
+add_library_contents_custom()
+{
+	if (( $# != 0 )) ; then
+		echo "internal error: expected 0 arguments, got $#" 1>&2
+		exit 1
+	fi
+
+	add_library 1 0 1 0 "STK" "L80"  "550V"  "CHG0"
+	add_library 2 0 2 0 "STK" "L80"  "550V"  "CHG1"
+	add_library 3 0 3 0 "STK" "L80"  "550V"  "CHG2"
+	add_library 4 0 4 0 "STK" "L80"  "550V"  "CHG3"
+	add_library 5 0 5 0 "STK" "L80"  "550V"  "CHG4"
+
+	add_ibm_ultrium_8_drive 11 0 11 0 "MAP0" 1 1
+	add_ibm_ultrium_8_drive 12 0 12 0 "MAP1" 2 1
+	add_ibm_ultrium_8_drive 13 0 13 0 "MAP2" 3 1
+	add_ibm_ultrium_8_drive 14 0 14 0 "MAP3" 4 1
+	add_ibm_ultrium_8_drive 15 0 15 0 "MAP4" 5 1
+
+}
+
 #
 # start of script
 #
@@ -454,5 +475,5 @@ fi
 echo '===>' "Generating: $DEST_DIR/$DEVICE_CONF ..."
 (
 	generate_static_comments
-	add_library_contents_10
+	add_library_contents_custom
 ) > $DEST_DIR/$DEVICE_CONF
